# Mac Mini M2 Server Configuration
# Central configuration file for the TILSIT server setup

# System Configuration
system:
  hostname: "TILSIT"        # Server hostname
  users:
    admin:
      name: "andrew.rich@gmail.com"  # iCloud-based admin user
      admin: true                    # Has admin privileges
    operator:
      name: "operator"      # Local non-admin user
      admin: false          # No admin privileges

# Hardware Configuration
hardware:
  model: "Mac Mini M2"
  resources:
    # Resource allocation for container runtime
    cpu_limit: 4            # Number of CPUs for container runtime
    memory_limit: 8         # GB of RAM for container runtime
    disk_limit: 100         # GB of disk for container runtime

# Network Configuration
network:
  # If true, configure static IP (requires manual setup in System Preferences)
  static_ip: true
  # Firewall configuration
  firewall:
    enabled: true
    stealth_mode: true
    allowed_services:
      - "ssh"
      - "http"
      - "https"
      - "32400"             # Plex port

# Remote Access Configuration
remote_access:
  # SSH configuration
  ssh:
    enabled: true
    port: 22                # Standard SSH port
    password_auth: false    # Use key-based authentication only
  # Apple Remote Desktop configuration
  remote_management:
    enabled: true

# NAS Configuration
nas:
  enabled: true
  mount_type: "nfs"         # Options: nfs, smb, afp
  mounts:
    - name: "Media"
      server: "nas.local"
      share: "/volume/Media"
      mount_point: "/Users/operator/NAS/Media"
      options: "rw,resvport,locallocks"
    - name: "TV"
      server: "nas.local"
      share: "/volume/TV"
      mount_point: "/Users/operator/NAS/TV"
      options: "rw,resvport,locallocks"
    - name: "Movies"
      server: "nas.local"
      share: "/volume/Movies"
      mount_point: "/Users/operator/NAS/Movies"
      options: "rw,resvport,locallocks"
    - name: "Music"
      server: "nas.local"
      share: "/volume/Music"
      mount_point: "/Users/operator/NAS/Music"
      options: "rw,resvport,locallocks"

# Container Runtime Configuration
containers:
  runtime: "colima"          # Lightweight alternative to Docker Desktop
  configuration:
    cpu: 4
    memory: 8
    disk: 100
  compose_dir: "/Users/operator/docker-data"
  data_dir: "/Users/operator/docker-data"

# Maintenance Configuration
maintenance:
  # System updates
  system_updates:
    enabled: true
    schedule: "weekly"      # Options: daily, weekly, monthly
    day: 1                  # Day of week (1 = Monday)
    hour: 3                 # 3 AM
  # Monitoring
  monitoring:
    enabled: true
    system_interval: 900    # 15 minutes
    network_interval: 3600  # 1 hour
  # Log rotation
  log_rotation:
    enabled: true
    max_size: 10485760      # 10MB
    keep_logs: 7            # Number of rotated logs to keep

# Installation Options
installation:
  # Homebrew packages
  packages:
    # Core formulae (CLI tools)
    cli_tools:
      - "bash"
      - "bash-completion@2"
      - "bat"
      - "brew-cask-completion"
      - "coreutils"
      - "ffmpeg"
      - "findutils"
      - "gawk"
      - "git"
      - "gnu-getopt"
      - "gnu-sed"
      - "gnu-tar"
      - "gnu-time"
      - "gnu-units"
      - "gnu-which"
      - "gnupg"
      - "grep"
      - "imagemagick"
      - "launchctl-completion"
      - "less"
      - "liquidprompt"
      - "open-completion"
      - "openssh"
      - "pipx"
      - "python@3.13"
      - "qrencode"
      - "ripgrep-all"
      - "rsync"
      - "shellcheck"
      - "speedtest"
      - "vim"
      # Additional tools needed for the server setup
      - "wget"
      - "curl"
      - "htop"
      - "jq"
      - "nmap"
      - "dockutil"
      - "mas"
      - "tmux"
      - "ansible"
      - "node"
      - "watch"
      - "yq"                # YAML processor
      # Container tools
      - "docker"
      - "docker-compose"
      - "docker-credential-helper"
      - "docker-buildx"
      - "colima"            # macOS container runtime
    # GUI applications (casks)
    cask_apps:
      # Personal applications
      - "1password"
      - "1password-cli"
      - "appcleaner"
      - "backblaze"
      - "bbedit"
      - "claude"
      - "dropbox"
      - "filebot"
      - "font-inconsolata"
      - "google-chrome"
      - "stay"
      - "zoom"
